//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userdetail
    {
        public int id { get; set; }
        public string fullName { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string roleType { get; set; }
        public string userName { get; set; }
        public string passowrd { get; set; }
        public bool isActive { get; set; }
        public string photoPath { get; set; }
    }
}
